apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-secrets
  namespace: zabbix
type: Opaque
stringData:
  db-password: "postgrespwdk8s"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-config
  namespace: zabbix
data:
  POSTGRES_USER: "zabbix"
  POSTGRES_DB: "zabbix"
  ZBX_SERVER_HOST: "zabbix-server"
  DB_SERVER_HOST: "postgres-service"
---
###
### POSTGRESQL (Configurado com Ephemeral Storage para Teste)
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: zabbix
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secrets
              key: db-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: zabbix
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
###
### ZABBIX SERVER
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
        ports:
        - containerPort: 10051
          name: zbx-server-port
        env:
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: DB_SERVER_HOST
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secrets
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  selector:
    app: zabbix-server
  ports:
  - protocol: TCP
    port: 10051
    targetPort: 10051
---
###
### ZABBIX FRONTEND
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix
  labels:
    app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ZBX_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: ZBX_SERVER_HOST
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: DB_SERVER_HOST
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: zabbix-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secrets
              key: db-password
        - name: PHP_TZ
          value: "America/Sao_Paulo"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-service
  namespace: zabbix
spec:
  type: NodePort
  selector:
    app: zabbix-web
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080